/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-11 00:59:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class context_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<div class=\"content-right\">\r\n");
      out.write("<div class=\"content-r-pic\"></div>\r\n");
      out.write("<div class=\"content-text\">\r\n");
      out.write("<div class=\"square\">\r\n");
      out.write("<div class=\"square-in\">\r\n");
      out.write("<div class=\"one\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"31\" colspan=\"3\"><span style=\"color:#0f3d66; font-size:14px;\">（进）采购管理</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"7%\" height=\"118\">&nbsp;</td>\r\n");
      out.write("    <td width=\"16%\"></td>\r\n");
      out.write("    <td width=\"77%\"><a href=\"#\"><img src=\"images/text_01.gif\" border=\"0\" width=\"115\" height=\"88\"/></a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购申请</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购订单</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">收货通知单</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购入库</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购发票</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div><!--\"one\"end-->\r\n");
      out.write("<div class=\"one\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"31\" colspan=\"3\"><span style=\"color:#0f3d66; font-size:14px;\">（销）销售管理</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"7%\" height=\"118\">&nbsp;</td>\r\n");
      out.write("    <td width=\"16%\"></td>\r\n");
      out.write("    <td width=\"77%\"><a href=\"#\"><img src=\"images/text_02.gif\" border=\"0\" width=\"115\" height=\"88\"/></a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购申请</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购订单</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">收货通知单</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购入库</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购发票</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div><!--\"one\"end-->\r\n");
      out.write("<div class=\"one\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"31\" colspan=\"3\"><span style=\"color:#0f3d66; font-size:14px;\">（存）库存管理</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"7%\" height=\"118\">&nbsp;</td>\r\n");
      out.write("    <td width=\"16%\"></td>\r\n");
      out.write("    <td width=\"77%\"><a href=\"#\"><img src=\"images/text_03.gif\" border=\"0\" width=\"115\" height=\"88\"/></a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购申请</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购订单</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">收货通知单</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购入库</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购发票</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div><!--\"one\"end-->\r\n");
      out.write("<div class=\"one\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"31\" colspan=\"3\"><span style=\"color:#0f3d66; font-size:14px;\">&nbsp;报表核算及分析</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"7%\" height=\"118\">&nbsp;</td>\r\n");
      out.write("    <td width=\"16%\"></td>\r\n");
      out.write("    <td width=\"77%\"><a href=\"#\"><img src=\"images/text_04.gif\" border=\"0\" width=\"115\" height=\"88\"/></a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购申请</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购订单</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">收货通知单</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购入库</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购发票</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div><!--\"one\"end-->\r\n");
      out.write("<div class=\"one\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"31\" colspan=\"3\"><span style=\"color:#0f3d66; font-size:14px;\">&nbsp;基础设置</span></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"7%\" height=\"118\">&nbsp;</td>\r\n");
      out.write("    <td width=\"16%\"></td>\r\n");
      out.write("    <td width=\"77%\"><a href=\"#\"><img src=\"images/text_05.gif\" border=\"0\" width=\"115\" height=\"88\"/></a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购申请</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购订单</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">收货通知单</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td colspan=\"2\" height=\"18\"><a class=\"cai\" href=\"#\">采购入库</a><span style=\"color:#7d94a9\">-></span> <a class=\"cai\" href=\"#\">采购发票</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div><!--\"one\"end-->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content-bbg\"><img src=\"images/content_bbg.jpg\" /></div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
