/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-11 00:59:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsps/tools/mask.jsp", Long.valueOf(1422147430000L));
    _jspx_dependants.put("/WEB-INF/jsps/tools/menu.jsp", Long.valueOf(1422560656000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title>北京蓝源进销存系统(教学版)-系统主页</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.3.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"head\">\r\n");
      out.write("\t\t\t<div class=\"head-left\">\r\n");
      out.write("\t\t\t\t<span style=\"font-weight:bold; color:#1f4906\">欢迎您-</span><br />\r\n");
      out.write("\t\t\t\t<span style=\"color:#4a940d\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session['loginEm'].name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"head-right\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"32%\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"emp_toChangePwd.action\" target=\"main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/head-l.gif\"\tborder=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"26%\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"emp_logout.action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/head-m.gif\"\tborder=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"7%\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"35%\"><a href=\"#\"><img src=\"images/head-r.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\tborder=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--\"head\"end-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left:2px;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/left-top.gif\" width=\"162\" height=\"25\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"left-bottom\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<link rel=\"stylesheet\"\thref=\"js/treeview/jquery.treeview.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\"\thref=\"js/treeview/screen.css\" />\r\n");
      out.write("\t\t<script src=\"js/jquery-1.8.3.js\"\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script\tsrc=\"js/treeview/jquery.cookie.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script\tsrc=\"js/treeview/jquery.treeview.min.js\"\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script\tsrc=\"js/treeview/jquery.treeview.async.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<ul id=\"black\" class=\"filetree\"></ul>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(\"#black\").treeview({\r\n");
      out.write("\t\t\turl : \"menu_showMenu.action\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--\"left-bottom\"end-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--\"left\"end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<iframe id=\"frame-contect\" src=\"page_context.action\"\r\n");
      out.write("\t\t\t\tstyle=\"width:848px;float:right;height:530px\" scrolling=\"no\"\r\n");
      out.write("\t\t\t\tname=\"main\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t\t<!--\"content-right\"end-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--\"content\"end-->\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<div style=\"margin-top:5px;\">\r\n");
      out.write("\t\t\t\t<table width=\"98%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"82%\"><img src=\"images/icon_1.gif\" />&nbsp; <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"lanyo\" href=\"www.itcast.cn\">传智播客 蓝源信息技术 2014</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"18%\" valign=\"middle\"><img src=\"images/icon_2.gif\" />&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lanyo\" href=\"#\">如有疑问请与技术人员联系</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--\"footer\"end-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--\"container\"end-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#pageOverlay {\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tz-index: 1987;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground: #ccc;\r\n");
      out.write("\tfilter: alpha(opacity = 70);\r\n");
      out.write("\topacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("/*IE6 fixed*/\r\n");
      out.write("* html {\r\n");
      out.write("\tbackground: url(*) fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* html body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* html #pageOverlay {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: expression(documentElement.scrollLeft +   documentElement.clientWidth -\r\n");
      out.write("\t\t  this.offsetWidth);\r\n");
      out.write("\ttop: expression(documentElement.scrollTop +   documentElement.clientHeight -\r\n");
      out.write("\t\t  this.offsetHeight);\r\n");
      out.write("}\r\n");
      out.write(".content-msg-size{\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("}\r\n");
      out.write(".content-msg-sizeh{\r\n");
      out.write("\theight:180px;\r\n");
      out.write("}\r\n");
      out.write(".content-msg-top{\r\n");
      out.write("\tbackground:url(\"images/content_tmsg.jpg\") no-repeat scroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write(".content-msg-body{\r\n");
      out.write("\twidth:298px;\r\n");
      out.write("}\r\n");
      out.write(".content-msg-bottom{\r\n");
      out.write("\tbackground:url(\"images/content_bmsg.jpg\") no-repeat scroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write(".context-msg{\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight:200px;\r\n");
      out.write("\tposition: absolute; \r\n");
      out.write("\tleft:40%; \r\n");
      out.write("\ttop:30%;\r\n");
      out.write("\tz-index:2000; \r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("}\r\n");
      out.write(".context-msg-txt{\r\n");
      out.write("\twidth:262px;\r\n");
      out.write("\theight:122px;\r\n");
      out.write("\tmargin-left:18px;\r\n");
      out.write("\tmargin-right:18px;\r\n");
      out.write("\tmargin-top:15px;\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tfont-family:'黑体';\r\n");
      out.write("\tcolor:#202677;\r\n");
      out.write("}\r\n");
      out.write(".context-msg-btn{\r\n");
      out.write("\twidth:262px;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\tmargin-left:18px;\r\n");
      out.write("\tmargin-right:18px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t\t// 获取对象\r\n");
      out.write("\t\tvar $ = function(id) {\r\n");
      out.write("\t\t\treturn document.getElementById(id);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// 遍历\r\n");
      out.write("\t\tvar each = function(a, b) {\r\n");
      out.write("\t\t\tfor ( var i = 0, len = a.length; i < len; i++)\r\n");
      out.write("\t\t\t\tb(a[i], i);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// 事件绑定\r\n");
      out.write("\t\tvar bind = function(obj, type, fn) {\r\n");
      out.write("\t\t\tif (obj.attachEvent) {\r\n");
      out.write("\t\t\t\tobj['e' + type + fn] = fn;\r\n");
      out.write("\t\t\t\tobj[type + fn] = function() {\r\n");
      out.write("\t\t\t\t\tobj['e' + type + fn](window.event);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tobj.attachEvent('on' + type, obj[type + fn]);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tobj.addEventListener(type, fn, false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t;\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t// 移除事件\r\n");
      out.write("\t\tvar unbind = function(obj, type, fn) {\r\n");
      out.write("\t\t\tif (obj.detachEvent) {\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tobj.detachEvent('on' + type, obj[type + fn]);\r\n");
      out.write("\t\t\t\t\tobj[type + fn] = null;\r\n");
      out.write("\t\t\t\t} catch (_) {\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tobj.removeEventListener(type, fn, false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t;\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t// 阻止浏览器默认行为\r\n");
      out.write("\t\tvar stopDefault = function(e) {\r\n");
      out.write("\t\t\te.preventDefault ? e.preventDefault() : e.returnValue = false;\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// 获取页面滚动条位置\r\n");
      out.write("\t\tvar getPage = function() {\r\n");
      out.write("\t\t\tvar dd = document.documentElement, db = document.body;\r\n");
      out.write("\t\t\treturn {\r\n");
      out.write("\t\t\t\tleft : Math.max(dd.scrollLeft, db.scrollLeft),\r\n");
      out.write("\t\t\t\ttop : Math.max(dd.scrollTop, db.scrollTop)\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t// 锁屏\r\n");
      out.write("\t\tvar lock = {\r\n");
      out.write("\t\t\tshow : function() {\r\n");
      out.write("\t\t\t\t$('pageOverlay').style.visibility = 'visible';\r\n");
      out.write("\t\t\t\tvar p = getPage(), left = p.left, top = p.top;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 页面鼠标操作限制\r\n");
      out.write("\t\t\t\tthis.mouse = function(evt) {\r\n");
      out.write("\t\t\t\t\tvar e = evt || window.event;\r\n");
      out.write("\t\t\t\t\tstopDefault(e);\r\n");
      out.write("\t\t\t\t\tscroll(left, top);\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\teach(\r\n");
      out.write("\t\t\t\t\t\t[ 'DOMMouseScroll', 'mousewheel', 'scroll',\r\n");
      out.write("\t\t\t\t\t\t\t\t'contextmenu' ], function(o, i) {\r\n");
      out.write("\t\t\t\t\t\t\tbind(document, o, lock.mouse);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t// 屏蔽特定按键: F5, Ctrl + R, Ctrl + A, Tab, Up, Down\r\n");
      out.write("\t\t\t\tthis.key = function(evt) {\r\n");
      out.write("\t\t\t\t\tvar e = evt || window.event, key = e.keyCode;\r\n");
      out.write("\t\t\t\t\tif ((key == 116) || (e.ctrlKey && key == 82)\r\n");
      out.write("\t\t\t\t\t\t\t|| (e.ctrlKey && key == 65) || (key == 9)\r\n");
      out.write("\t\t\t\t\t\t\t|| (key == 38) || (key == 40)) {\r\n");
      out.write("\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\te.keyCode = 0;\r\n");
      out.write("\t\t\t\t\t\t} catch (_) {\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t;\r\n");
      out.write("\t\t\t\t\t\tstopDefault(e);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tbind(document, 'keydown', lock.key);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tclose : function() {\r\n");
      out.write("\t\t\t\t$('pageOverlay').style.visibility = 'hidden';\r\n");
      out.write("\t\t\t\teach(\r\n");
      out.write("\t\t\t\t\t\t[ 'DOMMouseScroll', 'mousewheel', 'scroll',\r\n");
      out.write("\t\t\t\t\t\t\t\t'contextmenu' ], function(o, i) {\r\n");
      out.write("\t\t\t\t\t\t\tunbind(document, o, lock.mouse);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\tunbind(document, 'keydown', lock.key);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tbind(window, 'load', function() {\r\n");
      out.write("\t\t\t$('btn_ok').onclick = function() {\r\n");
      out.write("\t\t\t\t//显示遮罩的方法调用\r\n");
      out.write("\t\t\t\t//lock.show();\r\n");
      out.write("\t\t\t\t//以上为测试操作，以下为真实操作-----------------------------\r\n");
      out.write("\t\t\t\tlock.close();\r\n");
      out.write("\t\t\t\t$('frame-contect').src =  $('hid-action').value;\r\n");
      out.write("\t\t\t\t$('context-msg').style.display = \"none\";\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$('btn_cancel').onclick = function() {\r\n");
      out.write("\t\t\t\t//删除遮罩的方法调用\r\n");
      out.write("\t\t\t\tlock.close();\r\n");
      out.write("\t\t\t\t$('context-msg').style.display = \"none\";\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t*/\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"pageOverlay\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"context-msg\" class=\"context-msg\" id=\"context-msg\">\r\n");
      out.write("\t<div class=\"content-r-pic content-msg-size content-msg-top\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"content-text content-msg-size content-msg-sizeh content-msg-body\">\r\n");
      out.write("\t\t<div id=\"context-msg-text\" class=\"context-msg-txt\">\r\n");
      out.write("\t\t\t临时消息文字内容，测试专用，看看宽度临时消息文字内容，测试专用，看看宽度临时消息文字内容，测试专用，看看宽度\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<input id=\"hid-action\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t<div class=\"context-msg-btn\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t<input id=\"btn_ok\" type=\"image\" src=\"images/content_msg_btn_ok.jpg\"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<input id=\"btn_cancel\" type=\"image\" src=\"images/content_msg_btn_cancel.jpg\"/>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"content-bbg content-msg-size content-msg-bottom\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent(null);
    // /WEB-INF/jsps/tools/mask.jsp(187,2) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("#msg!=null and !#msg.isEmpty()");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\ttop.$('hid-action').value = 'content.action';\r\n");
        out.write("\t\t\ttop.$('context-msg-text').innerHTML='");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
          return true;
        out.write("';\r\n");
        out.write("\t\t\ttop.$('context-msg').style.display = \"block\";\r\n");
        out.write("\t\t\ttop.lock.show();\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
    // /WEB-INF/jsps/tools/mask.jsp(189,40) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("#msg");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
